spring:
  application:
    name: api_classmanager
  datasource:
    url: jdbc:postgresql://localhost:5432/api_classmanager_db
    username: api_classmanager_admin
    password: api_classmanager_admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#pgadmin user: api_classmanager@gmail.com
# pgadmin password: apiclassmanageradmin